### ISSUE TITLE
AzureVMCluster constructor hanging after creating the scheduler

### ISSUE THREAD

**Issue by manuelreyesgomez** [dask/dask-cloudprovider#275]
Installation of dask-cloudprovider[azure] (pip install dask-cloudprovider[azure] ) was done in a Python 3.8 new conda environment  
 
**Minimal Complete Verifiable Example**:

```python
from dask_cloudprovider.azure import AzureVMCluster
resource_group = "NGC-AML-Quick-Launch"
workspace_name = "NGC_AML_Quick_Launch_WS"
vnet="NGC-AML-Quick-Launch-vnet"
security_group="NGC-AML-Quick-Launch-nsg"
initial_node_count = 2
vm_size = "Standard_NC12s_v3"
location = "South Central US"
base_dockerfile = "rapidsai/rapidsai-core-nightly:0.18-cuda10.2-runtime-ubuntu18.04-py3.8"
EXTRA_PIP_PACKAGES = "dask-cloudprovider[azure]"

n_workers = initial_node_count

print(AzureVMCluster.get_cloud_init(
resource_group=resource_group,
location = location,
vnet=vnet,
security_group=security_group,
n_workers=n_workers,
vm_size=vm_size,
docker_image=base_dockerfile,
docker_args="--privileged",
auto_shutdown=False,
security=False,
env_vars={"EXTRA_PIP_PACKAGES": EXTRA_PIP_PACKAGES},
worker_class="dask_cuda.CUDAWorker"))

cluster = AzureVMCluster(
resource_group=resource_group,
location = location,
vnet=vnet,
security_group=security_group,
n_workers=n_workers,
vm_size=vm_size,
docker_image=base_dockerfile,
docker_args="--privileged",
auto_shutdown=False,
security=False,
env_vars={"EXTRA_PIP_PACKAGES": EXTRA_PIP_PACKAGES},
worker_class="dask_cuda.CUDAWorker")
```

Run printout:

```yaml
# Bootstrap
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - ubuntu-drivers-common

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]


runcmd:

  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker



  # Install NVIDIA driver
  - DEBIAN_FRONTEND=noninteractive ubuntu-drivers install

  # Install NVIDIA docker
  - curl -fsSL https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
  - curl -s -L https://nvidia.github.io/nvidia-docker/$(. /etc/os-release;echo $ID$VERSION_ID)/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
  - apt-get update -y
  - apt-get install -y nvidia-docker2
  - systemctl restart docker



  # Run container
  - 'docker run --net=host --gpus=all  -e EXTRA_PIP_PACKAGES="dask-cloudprovider[azure]" --privileged rapidsai/rapidsai-core-nightly:0.18-cuda10.2-runtime-ubuntu18.04-py3.8 dask-scheduler --version'

Creating scheduler instance
Assigned public IP
Network interface ready
Creating VM
Created VM dask-5ec07047-scheduler
Waiting for scheduler to run at 157.55.82.134:8786

```

**Code just hangs there**

The scheduler can be found on the Azure Portal and it does not seem to report issues on log file

Same code was working early today

**Environment**:

- Dask version:'2021.3.0'
- Python version: 3.8
- Operating System: WSL
- Install method (conda, pip, source):pip
